<?php
/**
 * Created by JetBrains PhpStorm.
 * User: Joseph.Cape
 * Date: 26/07/13
 * Time: 17:24
 * To change this template use File | Settings | File Templates.
 */

//include simplehtml_form.php

require_once(dirname(__FILE__) . '/../../config.php');

global $OUTPUT, $PAGE;
//$urlparams     =  required_param('value',0,PARAM_INT);
$processing    =   optional_param('processing',0,PARAM_INT);

$new_output = "";

$PAGE->set_context(context_system::instance());

//$PAGE->set_url($CFG->wwwroot . '/local/simpleajax_form/simpleajax_form_generator.php');
//Instantiate simplehtml_form
//$section = $DB->get_field('course_sections', 'section', array('id' => $sectionid, 'course' => $course->id), MUST_EXIST);
if($_GET["cid"]){
    $courseid=$_GET['cid'];


$query="SELECT *
FROM mdl_course_sections WHERE course='".$courseid."'";


    $course = $DB->get_records_sql($query);
$data.=html_writer::start_tag('option',array('value'=>"0"));
          $data.="Select Topic";
$data.=html_writer::end_tag('option');
    foreach ($course as $sec) {
//var_dump($sec);
if(empty($sec->name))
{
}
else{
$data.=html_writer::start_tag('option',array('value'=>$sec->id));
          $data.=$sec->name;
$data.=html_writer::end_tag('option');
}
    }
    $a=0;
    

  

    }
   




// AJAX Includes for normal mform Javascript code
// ... First we get the script generated by the Form API
 if($_GET["sid"]){
$data="";
    $course_id=$_GET['cid'];
    $section_id=$_GET['sid'];
if( $section_id!=0){
    $persection=$DB->get_field_sql("SELECT `sequence`
FROM `mdl_course_sections`WHERE `course`=".$course_id." AND `id` =$section_id");

    $persection=explode(",",$persection);

    $a=0;
    $R=array();
    $m= array( );
    foreach($persection as $course_moduleid){

        $module= $DB->get_field_sql("SELECT `module`
   FROM `mdl_course_modules`
   WHERE `id` = $course_moduleid");
        $instance= $DB->get_field_sql("SELECT  `instance`
   FROM `mdl_course_modules`
   WHERE `id`=$course_moduleid
   ");
         $moduleId= $DB->get_field_sql("SELECT  `module`
   FROM `mdl_course_modules`
   WHERE `id`=$course_moduleid
   ");
  $instace= $DB->get_field_sql("SELECT  `instance`
   FROM `mdl_course_modules`
   WHERE `id`=$course_moduleid
   ");
        $modname= $DB->get_field_sql("SELECT `name`
   FROM `mdl_modules`
   WHERE `id`=$module");
        $tablename="mdl_".$modname;
$m[$a]= $instace ."-".$modname;
       $R[$a]=$DB->get_field_sql("SELECT `name`
FROM $tablename
WHERE `id` =$instance
");
        $a=$a+1;
    }
$x=0;
 

 $data.=html_writer::start_tag('option',array('value'=>"",'slected'=>'selected'));
     
              $data.="Select Activity";
        $data.=html_writer::end_tag('option');


   foreach($R as $act){
            $data.=html_writer::start_tag('option',array('value'=>$m[$x]));
      $x=$x+1;
              $data.=$act;
        $data.=html_writer::end_tag('option');

    }
}

}

if (!$processing) {
    echo json_encode(array('html' => $data));
} else {
    echo json_encode(array('new_output'=>$new_output));
}


